name = "industrial-aps-viewer"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[vars]
APS_BUCKET_KEY = "sj-industrial-viewer-20260701"
APS_REGION = "US"

[[d1_databases]]
binding = "DB"
database_name = "industrial-aps-viewer"
database_id = "de488654-12d1-41ac-8dc5-6fad649e9572"
